services:
  wec-mailing:
    image: ghcr.io/dexstertv/wec-mailagent:latest
    container_name: wec-mailing-agent
    ports:
      - "8256:3000"
    volumes:
      - wec_data:/app/data
    restart: unless-stopped

volumes:
  wec_data:
