services:
  wec-mailing-agent:
    build: .
    container_name: wec-mailing-agent
    ports:
      - "0.0.0.0:8004:3000"
    env_file: .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
